enum eGeoSemantics
{
    WORLD,
    VIEW,
    PROJECTION,
    WORLDVIEW,
    VIEWPROJECTION,
    WORLDVIEWPROJECTION,

    WORLDINVERSE,
    VIEWINVERSE,
    PROJECTIONINVERSE,
    WORLDVIEWINVERSE,
    VIEWPROJECTIONINVERSE,
    WORLDVIEWPROJECTIONINVERSE,

    WORLDTRANSPOSE,
    VIEWTRANSPOSE,
    PROJECTIONTRANSPOSE,
    WORLDVIEWTRANSPOSE,
    VIEWPROJECTIONTRANSPOSE,
    WORLDVIEWPROJECTIONTRANSPOSE,

    NUM
}

enum eGeoAnotations
{
    Camera,
    Light,
    NUM
}